// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/helloworld/rpc/rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnicornRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnicornRequest) Reset()         { *m = UnicornRequest{} }
func (m *UnicornRequest) String() string { return proto.CompactTextString(m) }
func (*UnicornRequest) ProtoMessage()    {}
func (*UnicornRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5675d81d2c377bd0, []int{0}
}

func (m *UnicornRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnicornRequest.Unmarshal(m, b)
}
func (m *UnicornRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnicornRequest.Marshal(b, m, deterministic)
}
func (m *UnicornRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnicornRequest.Merge(m, src)
}
func (m *UnicornRequest) XXX_Size() int {
	return xxx_messageInfo_UnicornRequest.Size(m)
}
func (m *UnicornRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnicornRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnicornRequest proto.InternalMessageInfo

func (m *UnicornRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UnicornReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnicornReply) Reset()         { *m = UnicornReply{} }
func (m *UnicornReply) String() string { return proto.CompactTextString(m) }
func (*UnicornReply) ProtoMessage()    {}
func (*UnicornReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5675d81d2c377bd0, []int{1}
}

func (m *UnicornReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnicornReply.Unmarshal(m, b)
}
func (m *UnicornReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnicornReply.Marshal(b, m, deterministic)
}
func (m *UnicornReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnicornReply.Merge(m, src)
}
func (m *UnicornReply) XXX_Size() int {
	return xxx_messageInfo_UnicornReply.Size(m)
}
func (m *UnicornReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnicornReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnicornReply proto.InternalMessageInfo

func (m *UnicornReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UnicornRequest)(nil), "helloworld.rpc.UnicornRequest")
	proto.RegisterType((*UnicornReply)(nil), "helloworld.rpc.UnicornReply")
}

func init() { proto.RegisterFile("protobuf/helloworld/rpc/rpc.proto", fileDescriptor_5675d81d2c377bd0) }

var fileDescriptor_5675d81d2c377bd0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0xc0, 0x30,
	0x10, 0x85, 0x2d, 0x88, 0xe2, 0x21, 0x1d, 0x32, 0x15, 0x11, 0xd1, 0xe2, 0xd0, 0xc5, 0x04, 0x74,
	0x17, 0xd1, 0xd5, 0x41, 0x5a, 0x5c, 0xba, 0xa5, 0xf1, 0x6c, 0x53, 0x92, 0x5c, 0x4c, 0x53, 0x25,
	0xff, 0x5e, 0x2c, 0x56, 0xe9, 0xd0, 0xe1, 0xe0, 0x8e, 0xef, 0x1d, 0x1f, 0x3c, 0xb8, 0xf2, 0x81,
	0x22, 0x75, 0xf3, 0xbb, 0x18, 0xd0, 0x18, 0xfa, 0xa2, 0x60, 0xde, 0x44, 0xf0, 0xea, 0x67, 0xf8,
	0xc2, 0x58, 0xfe, 0x4f, 0x78, 0xf0, 0xaa, 0xbc, 0x86, 0xfc, 0xd5, 0x69, 0x45, 0xc1, 0xd5, 0xf8,
	0x31, 0xe3, 0x14, 0x19, 0x83, 0x43, 0x27, 0x2d, 0x16, 0xd9, 0x65, 0x56, 0x9d, 0xd4, 0xcb, 0x5e,
	0x56, 0x70, 0xfa, 0x97, 0xf2, 0x26, 0xb1, 0x02, 0x8e, 0x2d, 0x4e, 0x93, 0xec, 0xd7, 0xd8, 0x7a,
	0xde, 0xb6, 0x00, 0xf5, 0xcb, 0x53, 0x83, 0xe1, 0x53, 0x2b, 0x64, 0xcf, 0x00, 0x8d, 0x4c, 0xbf,
	0xaf, 0xec, 0x82, 0x6f, 0xe5, 0x7c, 0x6b, 0x3e, 0x3b, 0xdf, 0xe5, 0xde, 0xa4, 0xf2, 0xe0, 0xf1,
	0xa1, 0xbd, 0xef, 0x75, 0x1c, 0xe6, 0x8e, 0x2b, 0xb2, 0x62, 0x94, 0x38, 0x20, 0xb9, 0x51, 0x0b,
	0x4f, 0x26, 0xf5, 0x86, 0xe2, 0x8d, 0x25, 0x47, 0x01, 0x3d, 0x89, 0x9d, 0x1e, 0xba, 0xa3, 0x05,
	0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x48, 0x07, 0x49, 0x53, 0x29, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RPCServiceClient is the client API for RPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCServiceClient interface {
	SayUnicorn(ctx context.Context, in *UnicornRequest, opts ...grpc.CallOption) (*UnicornReply, error)
}

type rPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCServiceClient(cc grpc.ClientConnInterface) RPCServiceClient {
	return &rPCServiceClient{cc}
}

func (c *rPCServiceClient) SayUnicorn(ctx context.Context, in *UnicornRequest, opts ...grpc.CallOption) (*UnicornReply, error) {
	out := new(UnicornReply)
	err := c.cc.Invoke(ctx, "/helloworld.rpc.RPCService/SayUnicorn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServiceServer is the server API for RPCService service.
type RPCServiceServer interface {
	SayUnicorn(context.Context, *UnicornRequest) (*UnicornReply, error)
}

// UnimplementedRPCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRPCServiceServer struct {
}

func (*UnimplementedRPCServiceServer) SayUnicorn(ctx context.Context, req *UnicornRequest) (*UnicornReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayUnicorn not implemented")
}

func RegisterRPCServiceServer(s *grpc.Server, srv RPCServiceServer) {
	s.RegisterService(&_RPCService_serviceDesc, srv)
}

func _RPCService_SayUnicorn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnicornRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServiceServer).SayUnicorn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.rpc.RPCService/SayUnicorn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServiceServer).SayUnicorn(ctx, req.(*UnicornRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.rpc.RPCService",
	HandlerType: (*RPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayUnicorn",
			Handler:    _RPCService_SayUnicorn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/helloworld/rpc/rpc.proto",
}
